### ISSUE TITLE
프로젝트 피드백 - 작성자 : 최원장 튜터

### ISSUE THREAD

**Issue by wonee09** [Gon1782/IWANTHIS#51]
**i want this조 프로젝트 피드백**
- 의견 있으시면 알려주세요 👍 

1. 데이터 구조를 처음부터 아주 잘 잡고 시작했습니다. 사실 이 부분은 강의로 듣거나 한 부분은 아닐텐데 이런 감각을 스스로 깨우쳤다는게 대단하고 왠지 모르게 짠하기도 합니다.
2. 회원가입이랑 로그인을 왜 슬라이드로 왔다갔다 하게 했나요? 사용자가 모르지 않을까요?
3. dark모드를 잘 구현했어요.
4. 로그인 메뉴에서 패스워드를 입력했는데 안보이게 한건가요? 헷갈리지 않을까요?
5. 회원가입 시, 유효성 검증은 잘 되어있는 것 같습니다.
6. 마이페이지에서 이미지와 이름 변경하는 부분도 마냥 쉽지는 않았을 것 같은데, 그래도 잘 구현했습니다.
7. loading 중일 때, 스피너를 적절하게 넣어줘서 재밌게 봤어요. 스피너를 넣어준 조는 처음이지 않나요?
8. 댓글을 입력할 때, 키보드 영역 때문에 무슨 댓글을 입력하고 있는지가 안보여요. 조금 아쉽죠. --> 라고 적어놨는데, 오늘 시연영상을 보니깐 또 잘 되는것 같네요.
9. 잘 되는 페이지가 있고 안되는 페이지가 있나봐요.
10. 지금 dev 브랜치에 최종 소스가 올라가 있는 것 같은데 맞나요?
11. api 관련 코드와 util 관련 코드를 별도 분리한 부분 아주 좋습니다.
12. 애플리케이션의 특성상 카테고리를 지정하고 변경하고 하는 과정에서 지저분한 로직이 어쩔 수 없이 등장해요. 코드는 괜찮은데 이런 부분을 그럼 모든 조원들이 보고 알 수 있도록 주석 처리는 좀 해줘야 할 것 같아요. input은 뭐고 output은 뭐인지 정도는 알아야 사용할 수 있겠죠.
13. 컴포넌트도 전체를 다 풀어놓는 것이 아니라, 그 안에서 common 컴포넌트 그리고 screen 별 컴포넌트 등 여러가지로 나누어 관리했다면 좀 더 관리적 측면에서 유용했을 것 같아요.
14. Styled Component를 쓰면서 코드가 길어질 수 밖에 없는데, 분리가 필요해 보입니다.
15. 소스 곳곳에서 리팩토링 예정이라고 쓰여져 있으나, 되어있지는 않았습니다. 기대하겠습니다.

**Comment by Gon1782** [comment]
감사합니다!
