### ISSUE TITLE
프로젝트 피드백 - 작성자 : 이진수 튜터

### ISSUE THREAD

**Issue by 01-binary** [Gon1782/IWANTHIS#58]
### OverView

1. 영상에서 말로 간단하게라도 설명이 되었으면 더 좋았을 것 같습니다!
2. 회원가입 Validation 처리를 잘해주셨습니다.
3. Loading Spinner 처리가 아주 훌륭합니다.
4. 최종 버젼인 master branch의 이름을 main으로 바꾸시는 걸 추천드립니다. (https://velog.io/@gwsyl22/git-Github-branch-%EC%9D%B4%EB%A6%84-main%EC%9D%98-%EC%A0%95%EC%B2%B4%EB%8A%94)
5. 노션에 정리해주신 프로젝트 결과물 정리본이 아주 완성도가 높습니다.

**Comment by 01-binary** [comment]
https://github.com/Gon1782/IWANTHIS/blob/fef9a363dc0ce6b98dde21e8c5b802be12fd7971/db.json#L1-L12
db.json은 server폴더를 하나 만들어 그안에서 관리하면 좀더 깔끔해질거같습니다.

**Comment by 01-binary** [comment]
root에 assets이 존재하고 src/assets도 존재하는데 assets 폴더가 두개 존재해야할 이유가 있을까요?

**Comment by 01-binary** [comment]
src/assets 폴더에 하위폴더로 묶이지않은 파일들이 존재하는데 폴더로 구분하면 좀 더 깔끔합니다

**Comment by 01-binary** [comment]
https://github.com/Gon1782/IWANTHIS/blob/fef9a363dc0ce6b98dde21e8c5b802be12fd7971/src/common/util.js#L9-L20
함수로 만들어 export하는 걸 추천드립니다!

**Comment by 01-binary** [comment]
src/styles폴더에서 `styled.js`와 styled폴더안에 styled.jsx의 차이는 무엇인가요 ?

**Comment by 01-binary** [comment]
`common`, `components`, `screen` 등 전반적인 folder structure가 좋습니다!

**Comment by 01-binary** [comment]
rtk의 slice의 활용해 duck pattern을 만족하셨군요!
https://dinn.github.io/web/redux-ducks-pattern/

**Comment by 01-binary** [comment]
https://github.com/Gon1782/IWANTHIS/blob/fef9a363dc0ce6b98dde21e8c5b802be12fd7971/src/screen/EditList.jsx#L30-L33
`useReducer`을 사용해보는 것도 좋을꺼같아요!
https://react.vlpt.us/basic/20-useReducer.html

**Comment by 01-binary** [comment]
https://github.com/Gon1782/IWANTHIS/blob/fef9a363dc0ce6b98dde21e8c5b802be12fd7971/src/screen/EditList.jsx#L93-L112
`switch-true` 을 한번 공부하면 좋을꺼같아요! 
https://ui.toast.com/posts/ko_20210603

**Comment by 01-binary** [comment]
https://github.com/Gon1782/IWANTHIS/blob/fef9a363dc0ce6b98dde21e8c5b802be12fd7971/src/screen/Lists.jsx#L30-L31
dark모드 코드가 중복이 되는데 hook으로 따로 빼면 좋지않을까요 ??

**Comment by 01-binary** [comment]
https://github.com/Gon1782/IWANTHIS/blob/fef9a363dc0ce6b98dde21e8c5b802be12fd7971/src/hooks/usePickImage.jsx#L1-L30
참고하신 건가요 ?? 참고하셨더라도 아주 잘 활용하셨습니다!

**Comment by 01-binary** [comment]
전반적으로 코드 퀄리티가 아주 훌륭하고 commit convention도 잘 사용하시는거 같습니다.
리팩토링도 하신거같은데 나중에 시간될때 리팩토링을 해보는 경험은 레벨업이 많이 되는 경험일꺼에요ㅕ!

**Comment by Gon1782** [comment]
감사합니다 튜터님 도움 많이 됐습니다.

**Comment by Gon1782** [comment]
> root에 assets이 존재하고 src/assets도 존재하는데 assets 폴더가 두개 존재해야할 이유가 있을까요?

루트의 assets는 expo에서 로딩할때 사용하는 앱아이콘이고 src/assets는 저희가 사용하는 이미지입니다.
